###
GET  http://localhost:4000/api/employees/
###
POST  http://localhost:4000/api/employees/
Content-Type: application/json

{
    "name": "Jaime Sazo",
    "position": "Jr. Developer",
    "office": "Rome",
    "salary": "2000"
}
###
GET  http://localhost:4000/api/employees/5fc024c93641c6158cc9d383


###
DELETE   http://localhost:4000/api/employees/5fc024fb3641c6158cc9d384

###
PUT   http://localhost:4000/api/employees/5fc024c93641c6158cc9d383
Content-Type: application/json

{
    "salary": "100000"
}